package org.cocos2dxjs.core

import scala.language.implicitConversions
import scala.scalajs.js
import org.cocos2dxjs._
import org.cocos2dxjs.cocos2d.actions._
import org.cocos2dxjs.cocos2d.actions3d._
import org.cocos2dxjs.cocos2d.clippingnodes._
import org.cocos2dxjs.cocos2d.core._
import org.cocos2dxjs.cocos2d.core.basenodes._
import org.cocos2dxjs.cocos2d.core.cocoa._
import org.cocos2dxjs.cocos2d.core.eventmanager._
import org.cocos2dxjs.cocos2d.core.labelttf._
import org.cocos2dxjs.cocos2d.core.layers._
import org.cocos2dxjs.cocos2d.core.platform._
import org.cocos2dxjs.cocos2d.core.scenes._
import org.cocos2dxjs.cocos2d.core.sprites._
import org.cocos2dxjs.cocos2d.core.textures._
import org.cocos2dxjs.cocos2d.effects._
import org.cocos2dxjs.cocos2d.kazmath.gl._
import org.cocos2dxjs.cocos2d.kazmath._
import org.cocos2dxjs.cocos2d.labels._
import org.cocos2dxjs.cocos2d.menus._
import org.cocos2dxjs.cocos2d.motionstreak._
import org.cocos2dxjs.cocos2d.parallax._
import org.cocos2dxjs.cocos2d.particle._
import org.cocos2dxjs.cocos2d.physics._
import org.cocos2dxjs.cocos2d.progresstimer._
import org.cocos2dxjs.cocos2d.rendertexture._
import org.cocos2dxjs.cocos2d.shaders._
import org.cocos2dxjs.cocos2d.shapenodes._
import org.cocos2dxjs.cocos2d.textinput._
import org.cocos2dxjs.cocos2d.tilemap._
import org.cocos2dxjs.cocos2d.transitions._
import org.cocos2dxjs.extensions.ccpool._
import org.cocos2dxjs.extensions.ccui.baseclasses._
import org.cocos2dxjs.extensions.ccui.layouts._
import org.cocos2dxjs.extensions.ccui.system._
import org.cocos2dxjs.extensions.ccui.uiwidgets._
import org.cocos2dxjs.extensions.ccui.uiwidgets.scrollwidget._
import org.cocos2dxjs.extensions.cocostudio._
import org.cocos2dxjs.extensions.cocostudio.action._
import org.cocos2dxjs.extensions.cocostudio.armature._
import org.cocos2dxjs.extensions.cocostudio.armature.animation._
import org.cocos2dxjs.extensions.cocostudio.armature.datas._
import org.cocos2dxjs.extensions.cocostudio.armature.display._
import org.cocos2dxjs.extensions.cocostudio.armature.physics._
import org.cocos2dxjs.extensions.cocostudio.armature.utils._
import org.cocos2dxjs.extensions.cocostudio.components._
import org.cocos2dxjs.extensions.cocostudio.timeline._
import org.cocos2dxjs.extensions.cocostudio.trigger._
import org.cocos2dxjs.extensions.editbox._
import org.cocos2dxjs.extensions.gui.controlextension._
import org.cocos2dxjs.extensions.gui.scrollview._
import org.cocos2dxjs.extensions.spine._

object types {
  type DynFunction = js.Function with js.Dynamic
  type DynObject = js.Object with js.Dynamic
}

object Implicits {
  implicit def dynamicToccAsyncPool(d: types.DynObject):ccAsyncPool = d.asInstanceOf[ccAsyncPool]
  implicit def dynamicToccasync(d: types.DynObject):ccasync = d.asInstanceOf[ccasync]
  implicit def dynamicToccpath(d: types.DynObject):ccpath = d.asInstanceOf[ccpath]
  implicit def dynamicToccLoader(d: types.DynObject):ccLoader = d.asInstanceOf[ccLoader]
  implicit def dynamicToccgame(d: types.DynObject):ccgame = d.asInstanceOf[ccgame]
  implicit def dynamicToccAction(d: types.DynObject):ccAction = d.asInstanceOf[ccAction]
  implicit def dynamicToccFiniteTimeAction(d: types.DynObject):ccFiniteTimeAction = d.asInstanceOf[ccFiniteTimeAction]
  implicit def dynamicToccSpeed(d: types.DynObject):ccSpeed = d.asInstanceOf[ccSpeed]
  implicit def dynamicToccFollow(d: types.DynObject):ccFollow = d.asInstanceOf[ccFollow]
  implicit def dynamicToccCardinalSplineTo(d: types.DynObject):ccCardinalSplineTo = d.asInstanceOf[ccCardinalSplineTo]
  implicit def dynamicToccCardinalSplineBy(d: types.DynObject):ccCardinalSplineBy = d.asInstanceOf[ccCardinalSplineBy]
  implicit def dynamicToccCatmullRomTo(d: types.DynObject):ccCatmullRomTo = d.asInstanceOf[ccCatmullRomTo]
  implicit def dynamicToccCatmullRomBy(d: types.DynObject):ccCatmullRomBy = d.asInstanceOf[ccCatmullRomBy]
  implicit def dynamicToccActionEase(d: types.DynObject):ccActionEase = d.asInstanceOf[ccActionEase]
  implicit def dynamicToccEaseRateAction(d: types.DynObject):ccEaseRateAction = d.asInstanceOf[ccEaseRateAction]
  implicit def dynamicToccEaseIn(d: types.DynObject):ccEaseIn = d.asInstanceOf[ccEaseIn]
  implicit def dynamicToccEaseOut(d: types.DynObject):ccEaseOut = d.asInstanceOf[ccEaseOut]
  implicit def dynamicToccEaseInOut(d: types.DynObject):ccEaseInOut = d.asInstanceOf[ccEaseInOut]
  implicit def dynamicToccEaseExponentialIn(d: types.DynObject):ccEaseExponentialIn = d.asInstanceOf[ccEaseExponentialIn]
  implicit def dynamicToccEaseExponentialOut(d: types.DynObject):ccEaseExponentialOut = d.asInstanceOf[ccEaseExponentialOut]
  implicit def dynamicToccEaseExponentialInOut(d: types.DynObject):ccEaseExponentialInOut = d.asInstanceOf[ccEaseExponentialInOut]
  implicit def dynamicToccEaseSineIn(d: types.DynObject):ccEaseSineIn = d.asInstanceOf[ccEaseSineIn]
  implicit def dynamicToccEaseSineOut(d: types.DynObject):ccEaseSineOut = d.asInstanceOf[ccEaseSineOut]
  implicit def dynamicToccEaseSineInOut(d: types.DynObject):ccEaseSineInOut = d.asInstanceOf[ccEaseSineInOut]
  implicit def dynamicToccEaseElastic(d: types.DynObject):ccEaseElastic = d.asInstanceOf[ccEaseElastic]
  implicit def dynamicToccEaseElasticIn(d: types.DynObject):ccEaseElasticIn = d.asInstanceOf[ccEaseElasticIn]
  implicit def dynamicToccEaseElasticOut(d: types.DynObject):ccEaseElasticOut = d.asInstanceOf[ccEaseElasticOut]
  implicit def dynamicToccEaseElasticInOut(d: types.DynObject):ccEaseElasticInOut = d.asInstanceOf[ccEaseElasticInOut]
  implicit def dynamicToccEaseBounce(d: types.DynObject):ccEaseBounce = d.asInstanceOf[ccEaseBounce]
  implicit def dynamicToccEaseBounceIn(d: types.DynObject):ccEaseBounceIn = d.asInstanceOf[ccEaseBounceIn]
  implicit def dynamicToccEaseBounceOut(d: types.DynObject):ccEaseBounceOut = d.asInstanceOf[ccEaseBounceOut]
  implicit def dynamicToccEaseBounceInOut(d: types.DynObject):ccEaseBounceInOut = d.asInstanceOf[ccEaseBounceInOut]
  implicit def dynamicToccEaseBackIn(d: types.DynObject):ccEaseBackIn = d.asInstanceOf[ccEaseBackIn]
  implicit def dynamicToccEaseBackOut(d: types.DynObject):ccEaseBackOut = d.asInstanceOf[ccEaseBackOut]
  implicit def dynamicToccEaseBackInOut(d: types.DynObject):ccEaseBackInOut = d.asInstanceOf[ccEaseBackInOut]
  implicit def dynamicToccEaseBezierAction(d: types.DynObject):ccEaseBezierAction = d.asInstanceOf[ccEaseBezierAction]
  implicit def dynamicToccEaseQuadraticActionIn(d: types.DynObject):ccEaseQuadraticActionIn = d.asInstanceOf[ccEaseQuadraticActionIn]
  implicit def dynamicToccEaseQuadraticActionOut(d: types.DynObject):ccEaseQuadraticActionOut = d.asInstanceOf[ccEaseQuadraticActionOut]
  implicit def dynamicToccEaseQuadraticActionInOut(d: types.DynObject):ccEaseQuadraticActionInOut = d.asInstanceOf[ccEaseQuadraticActionInOut]
  implicit def dynamicToccEaseQuarticActionIn(d: types.DynObject):ccEaseQuarticActionIn = d.asInstanceOf[ccEaseQuarticActionIn]
  implicit def dynamicToccEaseQuarticActionOut(d: types.DynObject):ccEaseQuarticActionOut = d.asInstanceOf[ccEaseQuarticActionOut]
  implicit def dynamicToccEaseQuarticActionInOut(d: types.DynObject):ccEaseQuarticActionInOut = d.asInstanceOf[ccEaseQuarticActionInOut]
  implicit def dynamicToccEaseQuinticActionIn(d: types.DynObject):ccEaseQuinticActionIn = d.asInstanceOf[ccEaseQuinticActionIn]
  implicit def dynamicToccEaseQuinticActionOut(d: types.DynObject):ccEaseQuinticActionOut = d.asInstanceOf[ccEaseQuinticActionOut]
  implicit def dynamicToccEaseQuinticActionInOut(d: types.DynObject):ccEaseQuinticActionInOut = d.asInstanceOf[ccEaseQuinticActionInOut]
  implicit def dynamicToccEaseCircleActionIn(d: types.DynObject):ccEaseCircleActionIn = d.asInstanceOf[ccEaseCircleActionIn]
  implicit def dynamicToccEaseCircleActionOut(d: types.DynObject):ccEaseCircleActionOut = d.asInstanceOf[ccEaseCircleActionOut]
  implicit def dynamicToccEaseCircleActionInOut(d: types.DynObject):ccEaseCircleActionInOut = d.asInstanceOf[ccEaseCircleActionInOut]
  implicit def dynamicToccEaseCubicActionIn(d: types.DynObject):ccEaseCubicActionIn = d.asInstanceOf[ccEaseCubicActionIn]
  implicit def dynamicToccEaseCubicActionOut(d: types.DynObject):ccEaseCubicActionOut = d.asInstanceOf[ccEaseCubicActionOut]
  implicit def dynamicToccEaseCubicActionInOut(d: types.DynObject):ccEaseCubicActionInOut = d.asInstanceOf[ccEaseCubicActionInOut]
  implicit def dynamicToccActionInstant(d: types.DynObject):ccActionInstant = d.asInstanceOf[ccActionInstant]
  implicit def dynamicToccShow(d: types.DynObject):ccShow = d.asInstanceOf[ccShow]
  implicit def dynamicToccHide(d: types.DynObject):ccHide = d.asInstanceOf[ccHide]
  implicit def dynamicToccToggleVisibility(d: types.DynObject):ccToggleVisibility = d.asInstanceOf[ccToggleVisibility]
  implicit def dynamicToccRemoveSelf(d: types.DynObject):ccRemoveSelf = d.asInstanceOf[ccRemoveSelf]
  implicit def dynamicToccFlipX(d: types.DynObject):ccFlipX = d.asInstanceOf[ccFlipX]
  implicit def dynamicToccFlipY(d: types.DynObject):ccFlipY = d.asInstanceOf[ccFlipY]
  implicit def dynamicToccPlace(d: types.DynObject):ccPlace = d.asInstanceOf[ccPlace]
  implicit def dynamicToccCallFunc(d: types.DynObject):ccCallFunc = d.asInstanceOf[ccCallFunc]
  implicit def dynamicToccActionInterval(d: types.DynObject):ccActionInterval = d.asInstanceOf[ccActionInterval]
  implicit def dynamicToccSequence(d: types.DynObject):ccSequence = d.asInstanceOf[ccSequence]
  implicit def dynamicToccRepeat(d: types.DynObject):ccRepeat = d.asInstanceOf[ccRepeat]
  implicit def dynamicToccRepeatForever(d: types.DynObject):ccRepeatForever = d.asInstanceOf[ccRepeatForever]
  implicit def dynamicToccSpawn(d: types.DynObject):ccSpawn = d.asInstanceOf[ccSpawn]
  implicit def dynamicToccRotateTo(d: types.DynObject):ccRotateTo = d.asInstanceOf[ccRotateTo]
  implicit def dynamicToccRotateBy(d: types.DynObject):ccRotateBy = d.asInstanceOf[ccRotateBy]
  implicit def dynamicToccMoveBy(d: types.DynObject):ccMoveBy = d.asInstanceOf[ccMoveBy]
  implicit def dynamicToccMoveTo(d: types.DynObject):ccMoveTo = d.asInstanceOf[ccMoveTo]
  implicit def dynamicToccSkewTo(d: types.DynObject):ccSkewTo = d.asInstanceOf[ccSkewTo]
  implicit def dynamicToccSkewBy(d: types.DynObject):ccSkewBy = d.asInstanceOf[ccSkewBy]
  implicit def dynamicToccJumpBy(d: types.DynObject):ccJumpBy = d.asInstanceOf[ccJumpBy]
  implicit def dynamicToccJumpTo(d: types.DynObject):ccJumpTo = d.asInstanceOf[ccJumpTo]
  implicit def dynamicToccBezierBy(d: types.DynObject):ccBezierBy = d.asInstanceOf[ccBezierBy]
  implicit def dynamicToccBezierTo(d: types.DynObject):ccBezierTo = d.asInstanceOf[ccBezierTo]
  implicit def dynamicToccScaleTo(d: types.DynObject):ccScaleTo = d.asInstanceOf[ccScaleTo]
  implicit def dynamicToccScaleBy(d: types.DynObject):ccScaleBy = d.asInstanceOf[ccScaleBy]
  implicit def dynamicToccBlink(d: types.DynObject):ccBlink = d.asInstanceOf[ccBlink]
  implicit def dynamicToccFadeTo(d: types.DynObject):ccFadeTo = d.asInstanceOf[ccFadeTo]
  implicit def dynamicToccFadeIn(d: types.DynObject):ccFadeIn = d.asInstanceOf[ccFadeIn]
  implicit def dynamicToccFadeOut(d: types.DynObject):ccFadeOut = d.asInstanceOf[ccFadeOut]
  implicit def dynamicToccTintTo(d: types.DynObject):ccTintTo = d.asInstanceOf[ccTintTo]
  implicit def dynamicToccTintBy(d: types.DynObject):ccTintBy = d.asInstanceOf[ccTintBy]
  implicit def dynamicToccDelayTime(d: types.DynObject):ccDelayTime = d.asInstanceOf[ccDelayTime]
  implicit def dynamicToccReverseTime(d: types.DynObject):ccReverseTime = d.asInstanceOf[ccReverseTime]
  implicit def dynamicToccAnimate(d: types.DynObject):ccAnimate = d.asInstanceOf[ccAnimate]
  implicit def dynamicToccTargetedAction(d: types.DynObject):ccTargetedAction = d.asInstanceOf[ccTargetedAction]
  implicit def dynamicToccActionTweenDelegate(d: types.DynObject):ccActionTweenDelegate = d.asInstanceOf[ccActionTweenDelegate]
  implicit def dynamicToccActionTween(d: types.DynObject):ccActionTween = d.asInstanceOf[ccActionTween]
  implicit def dynamicToccGridAction(d: types.DynObject):ccGridAction = d.asInstanceOf[ccGridAction]
  implicit def dynamicToccGrid3DAction(d: types.DynObject):ccGrid3DAction = d.asInstanceOf[ccGrid3DAction]
  implicit def dynamicToccTiledGrid3DAction(d: types.DynObject):ccTiledGrid3DAction = d.asInstanceOf[ccTiledGrid3DAction]
  implicit def dynamicToccStopGrid(d: types.DynObject):ccStopGrid = d.asInstanceOf[ccStopGrid]
  implicit def dynamicToccReuseGrid(d: types.DynObject):ccReuseGrid = d.asInstanceOf[ccReuseGrid]
  implicit def dynamicToccWaves3D(d: types.DynObject):ccWaves3D = d.asInstanceOf[ccWaves3D]
  implicit def dynamicToccFlipX3D(d: types.DynObject):ccFlipX3D = d.asInstanceOf[ccFlipX3D]
  implicit def dynamicToccFlipY3D(d: types.DynObject):ccFlipY3D = d.asInstanceOf[ccFlipY3D]
  implicit def dynamicToccLens3D(d: types.DynObject):ccLens3D = d.asInstanceOf[ccLens3D]
  implicit def dynamicToccRipple3D(d: types.DynObject):ccRipple3D = d.asInstanceOf[ccRipple3D]
  implicit def dynamicToccShaky3D(d: types.DynObject):ccShaky3D = d.asInstanceOf[ccShaky3D]
  implicit def dynamicToccLiquid(d: types.DynObject):ccLiquid = d.asInstanceOf[ccLiquid]
  implicit def dynamicToccWaves(d: types.DynObject):ccWaves = d.asInstanceOf[ccWaves]
  implicit def dynamicToccTwirl(d: types.DynObject):ccTwirl = d.asInstanceOf[ccTwirl]
  implicit def dynamicToccPageTurn3D(d: types.DynObject):ccPageTurn3D = d.asInstanceOf[ccPageTurn3D]
  implicit def dynamicToccShakyTiles3D(d: types.DynObject):ccShakyTiles3D = d.asInstanceOf[ccShakyTiles3D]
  implicit def dynamicToccShatteredTiles3D(d: types.DynObject):ccShatteredTiles3D = d.asInstanceOf[ccShatteredTiles3D]
  implicit def dynamicToccTile(d: types.DynObject):ccTile = d.asInstanceOf[ccTile]
  implicit def dynamicToccShuffleTiles(d: types.DynObject):ccShuffleTiles = d.asInstanceOf[ccShuffleTiles]
  implicit def dynamicToccFadeOutTRTiles(d: types.DynObject):ccFadeOutTRTiles = d.asInstanceOf[ccFadeOutTRTiles]
  implicit def dynamicToccFadeOutBLTiles(d: types.DynObject):ccFadeOutBLTiles = d.asInstanceOf[ccFadeOutBLTiles]
  implicit def dynamicToccFadeOutUpTiles(d: types.DynObject):ccFadeOutUpTiles = d.asInstanceOf[ccFadeOutUpTiles]
  implicit def dynamicToccFadeOutDownTiles(d: types.DynObject):ccFadeOutDownTiles = d.asInstanceOf[ccFadeOutDownTiles]
  implicit def dynamicToccTurnOffTiles(d: types.DynObject):ccTurnOffTiles = d.asInstanceOf[ccTurnOffTiles]
  implicit def dynamicToccWavesTiles3D(d: types.DynObject):ccWavesTiles3D = d.asInstanceOf[ccWavesTiles3D]
  implicit def dynamicToccJumpTiles3D(d: types.DynObject):ccJumpTiles3D = d.asInstanceOf[ccJumpTiles3D]
  implicit def dynamicToccSplitRows(d: types.DynObject):ccSplitRows = d.asInstanceOf[ccSplitRows]
  implicit def dynamicToccSplitCols(d: types.DynObject):ccSplitCols = d.asInstanceOf[ccSplitCols]
  implicit def dynamicToccClippingNode(d: types.DynObject):ccClippingNode = d.asInstanceOf[ccClippingNode]
  implicit def dynamicToccHashElement(d: types.DynObject):ccHashElement = d.asInstanceOf[ccHashElement]
  implicit def dynamicToccActionManager(d: types.DynObject):ccActionManager = d.asInstanceOf[ccActionManager]
  implicit def dynamicToccconfiguration(d: types.DynObject):ccconfiguration = d.asInstanceOf[ccconfiguration]
  implicit def dynamicToccDirector(d: types.DynObject):ccDirector = d.asInstanceOf[ccDirector]
  implicit def dynamicToccDirectorDelegate(d: types.DynObject):ccDirectorDelegate = d.asInstanceOf[ccDirectorDelegate]
  implicit def dynamicToccDrawingPrimitiveCanvas(d: types.DynObject):ccDrawingPrimitiveCanvas = d.asInstanceOf[ccDrawingPrimitiveCanvas]
  implicit def dynamicToccDrawingPrimitiveWebGL(d: types.DynObject):ccDrawingPrimitiveWebGL = d.asInstanceOf[ccDrawingPrimitiveWebGL]
  implicit def dynamicToccScheduler(d: types.DynObject):ccScheduler = d.asInstanceOf[ccScheduler]
  implicit def dynamicToccAtlasNode(d: types.DynObject):ccAtlasNode = d.asInstanceOf[ccAtlasNode]
  implicit def dynamicToccNode(d: types.DynObject):ccNode = d.asInstanceOf[ccNode]
  implicit def dynamicToccAffineTransform(d: types.DynObject):ccAffineTransform = d.asInstanceOf[ccAffineTransform]
  implicit def dynamicToccPoint(d: types.DynObject):ccPoint = d.asInstanceOf[ccPoint]
  implicit def dynamicToccSize(d: types.DynObject):ccSize = d.asInstanceOf[ccSize]
  implicit def dynamicToccRect(d: types.DynObject):ccRect = d.asInstanceOf[ccRect]
  implicit def dynamicToccEvent(d: types.DynObject):ccEvent = d.asInstanceOf[ccEvent]
  implicit def dynamicToccEventCustom(d: types.DynObject):ccEventCustom = d.asInstanceOf[ccEventCustom]
  implicit def dynamicToccEventMouse(d: types.DynObject):ccEventMouse = d.asInstanceOf[ccEventMouse]
  implicit def dynamicToccEventTouch(d: types.DynObject):ccEventTouch = d.asInstanceOf[ccEventTouch]
  implicit def dynamicToccEventFocus(d: types.DynObject):ccEventFocus = d.asInstanceOf[ccEventFocus]
  implicit def dynamicToccEventAcceleration(d: types.DynObject):ccEventAcceleration = d.asInstanceOf[ccEventAcceleration]
  implicit def dynamicToccEventKeyboard(d: types.DynObject):ccEventKeyboard = d.asInstanceOf[ccEventKeyboard]
  implicit def dynamicToccEventListener(d: types.DynObject):ccEventListener = d.asInstanceOf[ccEventListener]
  implicit def dynamicTocceventManager(d: types.DynObject):cceventManager = d.asInstanceOf[cceventManager]
  implicit def dynamicToccTouch(d: types.DynObject):ccTouch = d.asInstanceOf[ccTouch]
  implicit def dynamicToccLabelTTF(d: types.DynObject):ccLabelTTF = d.asInstanceOf[ccLabelTTF]
  implicit def dynamicToccLayer(d: types.DynObject):ccLayer = d.asInstanceOf[ccLayer]
  implicit def dynamicToccLayerColor(d: types.DynObject):ccLayerColor = d.asInstanceOf[ccLayerColor]
  implicit def dynamicToccLayerGradient(d: types.DynObject):ccLayerGradient = d.asInstanceOf[ccLayerGradient]
  implicit def dynamicToccLayerMultiplex(d: types.DynObject):ccLayerMultiplex = d.asInstanceOf[ccLayerMultiplex]
  implicit def dynamicToccClass(d: types.DynObject):ccClass = d.asInstanceOf[ccClass]
  implicit def dynamicToccEGLView(d: types.DynObject):ccEGLView = d.asInstanceOf[ccEGLView]
  implicit def dynamicToccContainerStrategy(d: types.DynObject):ccContainerStrategy = d.asInstanceOf[ccContainerStrategy]
  implicit def dynamicToccContentStrategy(d: types.DynObject):ccContentStrategy = d.asInstanceOf[ccContentStrategy]
  implicit def dynamicToccResolutionPolicy(d: types.DynObject):ccResolutionPolicy = d.asInstanceOf[ccResolutionPolicy]
  implicit def dynamicToccinputManager(d: types.DynObject):ccinputManager = d.asInstanceOf[ccinputManager]
  implicit def dynamicToccSAXParser(d: types.DynObject):ccSAXParser = d.asInstanceOf[ccSAXParser]
  implicit def dynamicToccPlistParser(d: types.DynObject):ccPlistParser = d.asInstanceOf[ccPlistParser]
  implicit def dynamicToccscreen(d: types.DynObject):ccscreen = d.asInstanceOf[ccscreen]
  implicit def dynamicToccColor(d: types.DynObject):ccColor = d.asInstanceOf[ccColor]
  implicit def dynamicToccAcceleration(d: types.DynObject):ccAcceleration = d.asInstanceOf[ccAcceleration]
  implicit def dynamicToccVertex2F(d: types.DynObject):ccVertex2F = d.asInstanceOf[ccVertex2F]
  implicit def dynamicToccVertex3F(d: types.DynObject):ccVertex3F = d.asInstanceOf[ccVertex3F]
  implicit def dynamicToccTex2F(d: types.DynObject):ccTex2F = d.asInstanceOf[ccTex2F]
  implicit def dynamicToccQuad2(d: types.DynObject):ccQuad2 = d.asInstanceOf[ccQuad2]
  implicit def dynamicToccQuad3(d: types.DynObject):ccQuad3 = d.asInstanceOf[ccQuad3]
  implicit def dynamicToccV3F_C4B_T2F(d: types.DynObject):ccV3F_C4B_T2F = d.asInstanceOf[ccV3F_C4B_T2F]
  implicit def dynamicToccV3F_C4B_T2F_Quad(d: types.DynObject):ccV3F_C4B_T2F_Quad = d.asInstanceOf[ccV3F_C4B_T2F_Quad]
  implicit def dynamicToccV2F_C4B_T2F(d: types.DynObject):ccV2F_C4B_T2F = d.asInstanceOf[ccV2F_C4B_T2F]
  implicit def dynamicToccV2F_C4B_T2F_Triangle(d: types.DynObject):ccV2F_C4B_T2F_Triangle = d.asInstanceOf[ccV2F_C4B_T2F_Triangle]
  implicit def dynamicToccBlendFunc(d: types.DynObject):ccBlendFunc = d.asInstanceOf[ccBlendFunc]
  implicit def dynamicToccFontDefinition(d: types.DynObject):ccFontDefinition = d.asInstanceOf[ccFontDefinition]
  implicit def dynamicToccvisibleRect(d: types.DynObject):ccvisibleRect = d.asInstanceOf[ccvisibleRect]
  implicit def dynamicToccLoaderScene(d: types.DynObject):ccLoaderScene = d.asInstanceOf[ccLoaderScene]
  implicit def dynamicToccScene(d: types.DynObject):ccScene = d.asInstanceOf[ccScene]
  implicit def dynamicToccAnimationFrame(d: types.DynObject):ccAnimationFrame = d.asInstanceOf[ccAnimationFrame]
  implicit def dynamicToccAnimation(d: types.DynObject):ccAnimation = d.asInstanceOf[ccAnimation]
  implicit def dynamicToccanimationCache(d: types.DynObject):ccanimationCache = d.asInstanceOf[ccanimationCache]
  implicit def dynamicToccBakeSprite(d: types.DynObject):ccBakeSprite = d.asInstanceOf[ccBakeSprite]
  implicit def dynamicToccSprite(d: types.DynObject):ccSprite = d.asInstanceOf[ccSprite]
  implicit def dynamicToccSpriteBatchNode(d: types.DynObject):ccSpriteBatchNode = d.asInstanceOf[ccSpriteBatchNode]
  implicit def dynamicToccSpriteFrame(d: types.DynObject):ccSpriteFrame = d.asInstanceOf[ccSpriteFrame]
  implicit def dynamicToccspriteFrameCache(d: types.DynObject):ccspriteFrameCache = d.asInstanceOf[ccspriteFrameCache]
  implicit def dynamicToccTextureAtlas(d: types.DynObject):ccTextureAtlas = d.asInstanceOf[ccTextureAtlas]
  implicit def dynamicTocctextureCache(d: types.DynObject):cctextureCache = d.asInstanceOf[cctextureCache]
  implicit def dynamicToccTexture2D(d: types.DynObject):ccTexture2D = d.asInstanceOf[ccTexture2D]
  implicit def dynamicToccGrabber(d: types.DynObject):ccGrabber = d.asInstanceOf[ccGrabber]
  implicit def dynamicToccGridBase(d: types.DynObject):ccGridBase = d.asInstanceOf[ccGridBase]
  implicit def dynamicToccGrid3D(d: types.DynObject):ccGrid3D = d.asInstanceOf[ccGrid3D]
  implicit def dynamicToccTiledGrid3D(d: types.DynObject):ccTiledGrid3D = d.asInstanceOf[ccTiledGrid3D]
  implicit def dynamicToccmathMatrix4Stack(d: types.DynObject):ccmathMatrix4Stack = d.asInstanceOf[ccmathMatrix4Stack]
  implicit def dynamicToccmathMatrix3(d: types.DynObject):ccmathMatrix3 = d.asInstanceOf[ccmathMatrix3]
  implicit def dynamicToccmathMatrix4(d: types.DynObject):ccmathMatrix4 = d.asInstanceOf[ccmathMatrix4]
  implicit def dynamicToccmathQuaternion(d: types.DynObject):ccmathQuaternion = d.asInstanceOf[ccmathQuaternion]
  implicit def dynamicToccmathVec3(d: types.DynObject):ccmathVec3 = d.asInstanceOf[ccmathVec3]
  implicit def dynamicToccLabelAtlas(d: types.DynObject):ccLabelAtlas = d.asInstanceOf[ccLabelAtlas]
  implicit def dynamicToccLabelBMFont(d: types.DynObject):ccLabelBMFont = d.asInstanceOf[ccLabelBMFont]
  implicit def dynamicToccMenu(d: types.DynObject):ccMenu = d.asInstanceOf[ccMenu]
  implicit def dynamicToccMenuItem(d: types.DynObject):ccMenuItem = d.asInstanceOf[ccMenuItem]
  implicit def dynamicToccMenuItemLabel(d: types.DynObject):ccMenuItemLabel = d.asInstanceOf[ccMenuItemLabel]
  implicit def dynamicToccMenuItemAtlasFont(d: types.DynObject):ccMenuItemAtlasFont = d.asInstanceOf[ccMenuItemAtlasFont]
  implicit def dynamicToccMenuItemFont(d: types.DynObject):ccMenuItemFont = d.asInstanceOf[ccMenuItemFont]
  implicit def dynamicToccMenuItemSprite(d: types.DynObject):ccMenuItemSprite = d.asInstanceOf[ccMenuItemSprite]
  implicit def dynamicToccMenuItemImage(d: types.DynObject):ccMenuItemImage = d.asInstanceOf[ccMenuItemImage]
  implicit def dynamicToccMenuItemToggle(d: types.DynObject):ccMenuItemToggle = d.asInstanceOf[ccMenuItemToggle]
  implicit def dynamicToccMotionStreak(d: types.DynObject):ccMotionStreak = d.asInstanceOf[ccMotionStreak]
  implicit def dynamicToccPointObject(d: types.DynObject):ccPointObject = d.asInstanceOf[ccPointObject]
  implicit def dynamicToccParallaxNode(d: types.DynObject):ccParallaxNode = d.asInstanceOf[ccParallaxNode]
  implicit def dynamicToccParticleBatchNode(d: types.DynObject):ccParticleBatchNode = d.asInstanceOf[ccParticleBatchNode]
  implicit def dynamicToccParticleFire(d: types.DynObject):ccParticleFire = d.asInstanceOf[ccParticleFire]
  implicit def dynamicToccParticleFireworks(d: types.DynObject):ccParticleFireworks = d.asInstanceOf[ccParticleFireworks]
  implicit def dynamicToccParticleSun(d: types.DynObject):ccParticleSun = d.asInstanceOf[ccParticleSun]
  implicit def dynamicToccParticleGalaxy(d: types.DynObject):ccParticleGalaxy = d.asInstanceOf[ccParticleGalaxy]
  implicit def dynamicToccParticleFlower(d: types.DynObject):ccParticleFlower = d.asInstanceOf[ccParticleFlower]
  implicit def dynamicToccParticleMeteor(d: types.DynObject):ccParticleMeteor = d.asInstanceOf[ccParticleMeteor]
  implicit def dynamicToccParticleSpiral(d: types.DynObject):ccParticleSpiral = d.asInstanceOf[ccParticleSpiral]
  implicit def dynamicToccParticleExplosion(d: types.DynObject):ccParticleExplosion = d.asInstanceOf[ccParticleExplosion]
  implicit def dynamicToccParticleSmoke(d: types.DynObject):ccParticleSmoke = d.asInstanceOf[ccParticleSmoke]
  implicit def dynamicToccParticleSnow(d: types.DynObject):ccParticleSnow = d.asInstanceOf[ccParticleSnow]
  implicit def dynamicToccParticleRain(d: types.DynObject):ccParticleRain = d.asInstanceOf[ccParticleRain]
  implicit def dynamicToccParticle(d: types.DynObject):ccParticle = d.asInstanceOf[ccParticle]
  implicit def dynamicToccParticleModeA(d: types.DynObject):ccParticleModeA = d.asInstanceOf[ccParticleModeA]
  implicit def dynamicToccParticleModeB(d: types.DynObject):ccParticleModeB = d.asInstanceOf[ccParticleModeB]
  implicit def dynamicToccParticleSystem(d: types.DynObject):ccParticleSystem = d.asInstanceOf[ccParticleSystem]
  implicit def dynamicToccParticleSystemModeA(d: types.DynObject):ccParticleSystemModeA = d.asInstanceOf[ccParticleSystemModeA]
  implicit def dynamicToccParticleSystemModeB(d: types.DynObject):ccParticleSystemModeB = d.asInstanceOf[ccParticleSystemModeB]
  implicit def dynamicTocctiffReader(d: types.DynObject):cctiffReader = d.asInstanceOf[cctiffReader]
  implicit def dynamicToccPhysicsDebugNode(d: types.DynObject):ccPhysicsDebugNode = d.asInstanceOf[ccPhysicsDebugNode]
  implicit def dynamicToccPhysicsSprite(d: types.DynObject):ccPhysicsSprite = d.asInstanceOf[ccPhysicsSprite]
  implicit def dynamicToccProgressTo(d: types.DynObject):ccProgressTo = d.asInstanceOf[ccProgressTo]
  implicit def dynamicToccProgressFromTo(d: types.DynObject):ccProgressFromTo = d.asInstanceOf[ccProgressFromTo]
  implicit def dynamicToccProgressTimer(d: types.DynObject):ccProgressTimer = d.asInstanceOf[ccProgressTimer]
  implicit def dynamicToccRenderTexture(d: types.DynObject):ccRenderTexture = d.asInstanceOf[ccRenderTexture]
  implicit def dynamicToccGLProgram(d: types.DynObject):ccGLProgram = d.asInstanceOf[ccGLProgram]
  implicit def dynamicToccshaderCache(d: types.DynObject):ccshaderCache = d.asInstanceOf[ccshaderCache]
  implicit def dynamicToccDrawNode(d: types.DynObject):ccDrawNode = d.asInstanceOf[ccDrawNode]
  implicit def dynamicToccIMEKeyboardNotificationInfo(d: types.DynObject):ccIMEKeyboardNotificationInfo = d.asInstanceOf[ccIMEKeyboardNotificationInfo]
  implicit def dynamicToccIMEDelegate(d: types.DynObject):ccIMEDelegate = d.asInstanceOf[ccIMEDelegate]
  implicit def dynamicToccimeDispatcher(d: types.DynObject):ccimeDispatcher = d.asInstanceOf[ccimeDispatcher]
  implicit def dynamicToccIMEDispatcherImpl(d: types.DynObject):ccIMEDispatcherImpl = d.asInstanceOf[ccIMEDispatcherImpl]
  implicit def dynamicToccTextFieldDelegate(d: types.DynObject):ccTextFieldDelegate = d.asInstanceOf[ccTextFieldDelegate]
  implicit def dynamicToccTextFieldTTF(d: types.DynObject):ccTextFieldTTF = d.asInstanceOf[ccTextFieldTTF]
  implicit def dynamicToccImageTGA(d: types.DynObject):ccImageTGA = d.asInstanceOf[ccImageTGA]
  implicit def dynamicToccBinaryStreamReader(d: types.DynObject):ccBinaryStreamReader = d.asInstanceOf[ccBinaryStreamReader]
  implicit def dynamicToccTMXLayer(d: types.DynObject):ccTMXLayer = d.asInstanceOf[ccTMXLayer]
  implicit def dynamicToccTMXObjectGroup(d: types.DynObject):ccTMXObjectGroup = d.asInstanceOf[ccTMXObjectGroup]
  implicit def dynamicToccTMXTiledMap(d: types.DynObject):ccTMXTiledMap = d.asInstanceOf[ccTMXTiledMap]
  implicit def dynamicToccTMXLayerInfo(d: types.DynObject):ccTMXLayerInfo = d.asInstanceOf[ccTMXLayerInfo]
  implicit def dynamicToccTMXTilesetInfo(d: types.DynObject):ccTMXTilesetInfo = d.asInstanceOf[ccTMXTilesetInfo]
  implicit def dynamicToccTMXMapInfo(d: types.DynObject):ccTMXMapInfo = d.asInstanceOf[ccTMXMapInfo]
  implicit def dynamicToccTransitionScene(d: types.DynObject):ccTransitionScene = d.asInstanceOf[ccTransitionScene]
  implicit def dynamicToccTransitionSceneOriented(d: types.DynObject):ccTransitionSceneOriented = d.asInstanceOf[ccTransitionSceneOriented]
  implicit def dynamicToccTransitionRotoZoom(d: types.DynObject):ccTransitionRotoZoom = d.asInstanceOf[ccTransitionRotoZoom]
  implicit def dynamicToccTransitionJumpZoom(d: types.DynObject):ccTransitionJumpZoom = d.asInstanceOf[ccTransitionJumpZoom]
  implicit def dynamicToccTransitionMoveInL(d: types.DynObject):ccTransitionMoveInL = d.asInstanceOf[ccTransitionMoveInL]
  implicit def dynamicToccTransitionMoveInR(d: types.DynObject):ccTransitionMoveInR = d.asInstanceOf[ccTransitionMoveInR]
  implicit def dynamicToccTransitionMoveInT(d: types.DynObject):ccTransitionMoveInT = d.asInstanceOf[ccTransitionMoveInT]
  implicit def dynamicToccTransitionMoveInB(d: types.DynObject):ccTransitionMoveInB = d.asInstanceOf[ccTransitionMoveInB]
  implicit def dynamicToccTransitionSlideInL(d: types.DynObject):ccTransitionSlideInL = d.asInstanceOf[ccTransitionSlideInL]
  implicit def dynamicToccTransitionSlideInR(d: types.DynObject):ccTransitionSlideInR = d.asInstanceOf[ccTransitionSlideInR]
  implicit def dynamicToccTransitionSlideInB(d: types.DynObject):ccTransitionSlideInB = d.asInstanceOf[ccTransitionSlideInB]
  implicit def dynamicToccTransitionSlideInT(d: types.DynObject):ccTransitionSlideInT = d.asInstanceOf[ccTransitionSlideInT]
  implicit def dynamicToccTransitionShrinkGrow(d: types.DynObject):ccTransitionShrinkGrow = d.asInstanceOf[ccTransitionShrinkGrow]
  implicit def dynamicToccTransitionFade(d: types.DynObject):ccTransitionFade = d.asInstanceOf[ccTransitionFade]
  implicit def dynamicToccTransitionCrossFade(d: types.DynObject):ccTransitionCrossFade = d.asInstanceOf[ccTransitionCrossFade]
  implicit def dynamicToccTransitionTurnOffTiles(d: types.DynObject):ccTransitionTurnOffTiles = d.asInstanceOf[ccTransitionTurnOffTiles]
  implicit def dynamicToccTransitionSplitCols(d: types.DynObject):ccTransitionSplitCols = d.asInstanceOf[ccTransitionSplitCols]
  implicit def dynamicToccTransitionSplitRows(d: types.DynObject):ccTransitionSplitRows = d.asInstanceOf[ccTransitionSplitRows]
  implicit def dynamicToccTransitionFadeTR(d: types.DynObject):ccTransitionFadeTR = d.asInstanceOf[ccTransitionFadeTR]
  implicit def dynamicToccTransitionFadeBL(d: types.DynObject):ccTransitionFadeBL = d.asInstanceOf[ccTransitionFadeBL]
  implicit def dynamicToccTransitionFadeUp(d: types.DynObject):ccTransitionFadeUp = d.asInstanceOf[ccTransitionFadeUp]
  implicit def dynamicToccTransitionFadeDown(d: types.DynObject):ccTransitionFadeDown = d.asInstanceOf[ccTransitionFadeDown]
  implicit def dynamicToccTransitionPageTurn(d: types.DynObject):ccTransitionPageTurn = d.asInstanceOf[ccTransitionPageTurn]
  implicit def dynamicToccTransitionProgress(d: types.DynObject):ccTransitionProgress = d.asInstanceOf[ccTransitionProgress]
  implicit def dynamicToccTransitionProgressRadialCCW(d: types.DynObject):ccTransitionProgressRadialCCW = d.asInstanceOf[ccTransitionProgressRadialCCW]
  implicit def dynamicToccTransitionProgressRadialCW(d: types.DynObject):ccTransitionProgressRadialCW = d.asInstanceOf[ccTransitionProgressRadialCW]
  implicit def dynamicToccTransitionProgressHorizontal(d: types.DynObject):ccTransitionProgressHorizontal = d.asInstanceOf[ccTransitionProgressHorizontal]
  implicit def dynamicToccTransitionProgressVertical(d: types.DynObject):ccTransitionProgressVertical = d.asInstanceOf[ccTransitionProgressVertical]
  implicit def dynamicToccTransitionProgressInOut(d: types.DynObject):ccTransitionProgressInOut = d.asInstanceOf[ccTransitionProgressInOut]
  implicit def dynamicToccTransitionProgressOutIn(d: types.DynObject):ccTransitionProgressOutIn = d.asInstanceOf[ccTransitionProgressOutIn]
  implicit def dynamicToccpool(d: types.DynObject):ccpool = d.asInstanceOf[ccpool]
  implicit def dynamicToccProtectedNode(d: types.DynObject):ccProtectedNode = d.asInstanceOf[ccProtectedNode]
  implicit def dynamicToccuiScale9Sprite(d: types.DynObject):ccuiScale9Sprite = d.asInstanceOf[ccuiScale9Sprite]
  implicit def dynamicToccuiWidget(d: types.DynObject):ccuiWidget = d.asInstanceOf[ccuiWidget]
  implicit def dynamicToccuiHBox(d: types.DynObject):ccuiHBox = d.asInstanceOf[ccuiHBox]
  implicit def dynamicToccuiLayout(d: types.DynObject):ccuiLayout = d.asInstanceOf[ccuiLayout]
  implicit def dynamicToccuilinearVerticalLayoutManager(d: types.DynObject):ccuilinearVerticalLayoutManager = d.asInstanceOf[ccuilinearVerticalLayoutManager]
  implicit def dynamicToccuilinearHorizontalLayoutManager(d: types.DynObject):ccuilinearHorizontalLayoutManager = d.asInstanceOf[ccuilinearHorizontalLayoutManager]
  implicit def dynamicToccuirelativeLayoutManager(d: types.DynObject):ccuirelativeLayoutManager = d.asInstanceOf[ccuirelativeLayoutManager]
  implicit def dynamicToccuiMargin(d: types.DynObject):ccuiMargin = d.asInstanceOf[ccuiMargin]
  implicit def dynamicToccuiLayoutParameter(d: types.DynObject):ccuiLayoutParameter = d.asInstanceOf[ccuiLayoutParameter]
  implicit def dynamicToccuiLinearLayoutParameter(d: types.DynObject):ccuiLinearLayoutParameter = d.asInstanceOf[ccuiLinearLayoutParameter]
  implicit def dynamicToccuiRelativeLayoutParameter(d: types.DynObject):ccuiRelativeLayoutParameter = d.asInstanceOf[ccuiRelativeLayoutParameter]
  implicit def dynamicToccuiRelativeBox(d: types.DynObject):ccuiRelativeBox = d.asInstanceOf[ccuiRelativeBox]
  implicit def dynamicToccuiVBox(d: types.DynObject):ccuiVBox = d.asInstanceOf[ccuiVBox]
  implicit def dynamicToccuiClass(d: types.DynObject):ccuiClass = d.asInstanceOf[ccuiClass]
  implicit def dynamicToccuiNode(d: types.DynObject):ccuiNode = d.asInstanceOf[ccuiNode]
  implicit def dynamicToccuiProtectedNode(d: types.DynObject):ccuiProtectedNode = d.asInstanceOf[ccuiProtectedNode]
  implicit def dynamicToccuihelper(d: types.DynObject):ccuihelper = d.asInstanceOf[ccuihelper]
  implicit def dynamicToccuiButton(d: types.DynObject):ccuiButton = d.asInstanceOf[ccuiButton]
  implicit def dynamicToccuiCheckBox(d: types.DynObject):ccuiCheckBox = d.asInstanceOf[ccuiCheckBox]
  implicit def dynamicToccuiImageView(d: types.DynObject):ccuiImageView = d.asInstanceOf[ccuiImageView]
  implicit def dynamicToccuiLoadingBar(d: types.DynObject):ccuiLoadingBar = d.asInstanceOf[ccuiLoadingBar]
  implicit def dynamicToccuiRichElement(d: types.DynObject):ccuiRichElement = d.asInstanceOf[ccuiRichElement]
  implicit def dynamicToccuiRichElementText(d: types.DynObject):ccuiRichElementText = d.asInstanceOf[ccuiRichElementText]
  implicit def dynamicToccuiRichElementImage(d: types.DynObject):ccuiRichElementImage = d.asInstanceOf[ccuiRichElementImage]
  implicit def dynamicToccuiRichElementCustomNode(d: types.DynObject):ccuiRichElementCustomNode = d.asInstanceOf[ccuiRichElementCustomNode]
  implicit def dynamicToccuiRichText(d: types.DynObject):ccuiRichText = d.asInstanceOf[ccuiRichText]
  implicit def dynamicToccuiSlider(d: types.DynObject):ccuiSlider = d.asInstanceOf[ccuiSlider]
  implicit def dynamicToccuiText(d: types.DynObject):ccuiText = d.asInstanceOf[ccuiText]
  implicit def dynamicToccuiTextAtlas(d: types.DynObject):ccuiTextAtlas = d.asInstanceOf[ccuiTextAtlas]
  implicit def dynamicToccuiLabelBMFont(d: types.DynObject):ccuiLabelBMFont = d.asInstanceOf[ccuiLabelBMFont]
  implicit def dynamicToccuiTextField(d: types.DynObject):ccuiTextField = d.asInstanceOf[ccuiTextField]
  implicit def dynamicToccuiVideoPlayer(d: types.DynObject):ccuiVideoPlayer = d.asInstanceOf[ccuiVideoPlayer]
  implicit def dynamicToccuiWebView(d: types.DynObject):ccuiWebView = d.asInstanceOf[ccuiWebView]
  implicit def dynamicToccuiListView(d: types.DynObject):ccuiListView = d.asInstanceOf[ccuiListView]
  implicit def dynamicToccuiPageView(d: types.DynObject):ccuiPageView = d.asInstanceOf[ccuiPageView]
  implicit def dynamicToccuiPageViewIndicator(d: types.DynObject):ccuiPageViewIndicator = d.asInstanceOf[ccuiPageViewIndicator]
  implicit def dynamicToccuiScrollView(d: types.DynObject):ccuiScrollView = d.asInstanceOf[ccuiScrollView]
  implicit def dynamicToccuiScrollViewBar(d: types.DynObject):ccuiScrollViewBar = d.asInstanceOf[ccuiScrollViewBar]
  implicit def dynamicToccsClass(d: types.DynObject):ccsClass = d.asInstanceOf[ccsClass]
  implicit def dynamicToccsNode(d: types.DynObject):ccsNode = d.asInstanceOf[ccsNode]
  implicit def dynamicToccsSprite(d: types.DynObject):ccsSprite = d.asInstanceOf[ccsSprite]
  implicit def dynamicToccsComponent(d: types.DynObject):ccsComponent = d.asInstanceOf[ccsComponent]
  implicit def dynamicToccsActionFrame(d: types.DynObject):ccsActionFrame = d.asInstanceOf[ccsActionFrame]
  implicit def dynamicToccsActionMoveFrame(d: types.DynObject):ccsActionMoveFrame = d.asInstanceOf[ccsActionMoveFrame]
  implicit def dynamicToccsActionScaleFrame(d: types.DynObject):ccsActionScaleFrame = d.asInstanceOf[ccsActionScaleFrame]
  implicit def dynamicToccsActionRotationFrame(d: types.DynObject):ccsActionRotationFrame = d.asInstanceOf[ccsActionRotationFrame]
  implicit def dynamicToccsActionFadeFrame(d: types.DynObject):ccsActionFadeFrame = d.asInstanceOf[ccsActionFadeFrame]
  implicit def dynamicToccsActionTintFrame(d: types.DynObject):ccsActionTintFrame = d.asInstanceOf[ccsActionTintFrame]
  implicit def dynamicToccsactionManager(d: types.DynObject):ccsactionManager = d.asInstanceOf[ccsactionManager]
  implicit def dynamicToccsActionNode(d: types.DynObject):ccsActionNode = d.asInstanceOf[ccsActionNode]
  implicit def dynamicToccsActionObject(d: types.DynObject):ccsActionObject = d.asInstanceOf[ccsActionObject]
  implicit def dynamicToccsArmature(d: types.DynObject):ccsArmature = d.asInstanceOf[ccsArmature]
  implicit def dynamicToccsBone(d: types.DynObject):ccsBone = d.asInstanceOf[ccsBone]
  implicit def dynamicToccsAnimationEvent(d: types.DynObject):ccsAnimationEvent = d.asInstanceOf[ccsAnimationEvent]
  implicit def dynamicToccsMovementEvent(d: types.DynObject):ccsMovementEvent = d.asInstanceOf[ccsMovementEvent]
  implicit def dynamicToccsFrameEvent(d: types.DynObject):ccsFrameEvent = d.asInstanceOf[ccsFrameEvent]
  implicit def dynamicToccsArmatureAnimation(d: types.DynObject):ccsArmatureAnimation = d.asInstanceOf[ccsArmatureAnimation]
  implicit def dynamicToccsProcessBase(d: types.DynObject):ccsProcessBase = d.asInstanceOf[ccsProcessBase]
  implicit def dynamicToccsTween(d: types.DynObject):ccsTween = d.asInstanceOf[ccsTween]
  implicit def dynamicToccsBaseData(d: types.DynObject):ccsBaseData = d.asInstanceOf[ccsBaseData]
  implicit def dynamicToccsDisplayData(d: types.DynObject):ccsDisplayData = d.asInstanceOf[ccsDisplayData]
  implicit def dynamicToccsSpriteDisplayData(d: types.DynObject):ccsSpriteDisplayData = d.asInstanceOf[ccsSpriteDisplayData]
  implicit def dynamicToccsArmatureDisplayData(d: types.DynObject):ccsArmatureDisplayData = d.asInstanceOf[ccsArmatureDisplayData]
  implicit def dynamicToccsParticleDisplayData(d: types.DynObject):ccsParticleDisplayData = d.asInstanceOf[ccsParticleDisplayData]
  implicit def dynamicToccsBoneData(d: types.DynObject):ccsBoneData = d.asInstanceOf[ccsBoneData]
  implicit def dynamicToccsArmatureData(d: types.DynObject):ccsArmatureData = d.asInstanceOf[ccsArmatureData]
  implicit def dynamicToccsFrameData(d: types.DynObject):ccsFrameData = d.asInstanceOf[ccsFrameData]
  implicit def dynamicToccsMovementBoneData(d: types.DynObject):ccsMovementBoneData = d.asInstanceOf[ccsMovementBoneData]
  implicit def dynamicToccsMovementData(d: types.DynObject):ccsMovementData = d.asInstanceOf[ccsMovementData]
  implicit def dynamicToccsAnimationData(d: types.DynObject):ccsAnimationData = d.asInstanceOf[ccsAnimationData]
  implicit def dynamicToccsContourVertex2(d: types.DynObject):ccsContourVertex2 = d.asInstanceOf[ccsContourVertex2]
  implicit def dynamicToccsContourData(d: types.DynObject):ccsContourData = d.asInstanceOf[ccsContourData]
  implicit def dynamicToccsTextureData(d: types.DynObject):ccsTextureData = d.asInstanceOf[ccsTextureData]
  implicit def dynamicToccsBatchNode(d: types.DynObject):ccsBatchNode = d.asInstanceOf[ccsBatchNode]
  implicit def dynamicToccsDecorativeDisplay(d: types.DynObject):ccsDecorativeDisplay = d.asInstanceOf[ccsDecorativeDisplay]
  implicit def dynamicToccsDisplayManager(d: types.DynObject):ccsDisplayManager = d.asInstanceOf[ccsDisplayManager]
  implicit def dynamicToccsSkin(d: types.DynObject):ccsSkin = d.asInstanceOf[ccsSkin]
  implicit def dynamicToccsColliderFilter(d: types.DynObject):ccsColliderFilter = d.asInstanceOf[ccsColliderFilter]
  implicit def dynamicToccsColliderBody(d: types.DynObject):ccsColliderBody = d.asInstanceOf[ccsColliderBody]
  implicit def dynamicToccsColliderDetector(d: types.DynObject):ccsColliderDetector = d.asInstanceOf[ccsColliderDetector]
  implicit def dynamicToccsRelativeData(d: types.DynObject):ccsRelativeData = d.asInstanceOf[ccsRelativeData]
  implicit def dynamicToccsarmatureDataManager(d: types.DynObject):ccsarmatureDataManager = d.asInstanceOf[ccsarmatureDataManager]
  implicit def dynamicToccsDataInfo(d: types.DynObject):ccsDataInfo = d.asInstanceOf[ccsDataInfo]
  implicit def dynamicToccsdataReaderHelper(d: types.DynObject):ccsdataReaderHelper = d.asInstanceOf[ccsdataReaderHelper]
  implicit def dynamicToccsspriteFrameCacheHelper(d: types.DynObject):ccsspriteFrameCacheHelper = d.asInstanceOf[ccsspriteFrameCacheHelper]
  implicit def dynamicToccsTransformHelp(d: types.DynObject):ccsTransformHelp = d.asInstanceOf[ccsTransformHelp]
  implicit def dynamicToccsComAttribute(d: types.DynObject):ccsComAttribute = d.asInstanceOf[ccsComAttribute]
  implicit def dynamicToccsComAudio(d: types.DynObject):ccsComAudio = d.asInstanceOf[ccsComAudio]
  implicit def dynamicToccsComController(d: types.DynObject):ccsComController = d.asInstanceOf[ccsComController]
  implicit def dynamicToccsComRender(d: types.DynObject):ccsComRender = d.asInstanceOf[ccsComRender]
  implicit def dynamicToccComponent(d: types.DynObject):ccComponent = d.asInstanceOf[ccComponent]
  implicit def dynamicToccComponentContainer(d: types.DynObject):ccComponentContainer = d.asInstanceOf[ccComponentContainer]
  implicit def dynamicToccsActionTimelineData(d: types.DynObject):ccsActionTimelineData = d.asInstanceOf[ccsActionTimelineData]
  implicit def dynamicToccsActionTimeline(d: types.DynObject):ccsActionTimeline = d.asInstanceOf[ccsActionTimeline]
  implicit def dynamicToccsBoneNode(d: types.DynObject):ccsBoneNode = d.asInstanceOf[ccsBoneNode]
  implicit def dynamicToccsSkeletonNode(d: types.DynObject):ccsSkeletonNode = d.asInstanceOf[ccsSkeletonNode]
  implicit def dynamicToccsFrame(d: types.DynObject):ccsFrame = d.asInstanceOf[ccsFrame]
  implicit def dynamicToccsVisibleFrame(d: types.DynObject):ccsVisibleFrame = d.asInstanceOf[ccsVisibleFrame]
  implicit def dynamicToccsTextureFrame(d: types.DynObject):ccsTextureFrame = d.asInstanceOf[ccsTextureFrame]
  implicit def dynamicToccsRotationFrame(d: types.DynObject):ccsRotationFrame = d.asInstanceOf[ccsRotationFrame]
  implicit def dynamicToccsSkewFrame(d: types.DynObject):ccsSkewFrame = d.asInstanceOf[ccsSkewFrame]
  implicit def dynamicToccsRotationSkewFrame(d: types.DynObject):ccsRotationSkewFrame = d.asInstanceOf[ccsRotationSkewFrame]
  implicit def dynamicToccsPositionFrame(d: types.DynObject):ccsPositionFrame = d.asInstanceOf[ccsPositionFrame]
  implicit def dynamicToccsScaleFrame(d: types.DynObject):ccsScaleFrame = d.asInstanceOf[ccsScaleFrame]
  implicit def dynamicToccsAnchorPointFrame(d: types.DynObject):ccsAnchorPointFrame = d.asInstanceOf[ccsAnchorPointFrame]
  implicit def dynamicToccsInnerActionFrame(d: types.DynObject):ccsInnerActionFrame = d.asInstanceOf[ccsInnerActionFrame]
  implicit def dynamicToccsColorFrame(d: types.DynObject):ccsColorFrame = d.asInstanceOf[ccsColorFrame]
  implicit def dynamicToccsAlphaFrame(d: types.DynObject):ccsAlphaFrame = d.asInstanceOf[ccsAlphaFrame]
  implicit def dynamicToccsEventFrame(d: types.DynObject):ccsEventFrame = d.asInstanceOf[ccsEventFrame]
  implicit def dynamicToccsZOrderFrame(d: types.DynObject):ccsZOrderFrame = d.asInstanceOf[ccsZOrderFrame]
  implicit def dynamicToccsTimeline(d: types.DynObject):ccsTimeline = d.asInstanceOf[ccsTimeline]
  implicit def dynamicToccsobjectFactory(d: types.DynObject):ccsobjectFactory = d.asInstanceOf[ccsobjectFactory]
  implicit def dynamicToccsTInfo(d: types.DynObject):ccsTInfo = d.asInstanceOf[ccsTInfo]
  implicit def dynamicToccstriggerManager(d: types.DynObject):ccstriggerManager = d.asInstanceOf[ccstriggerManager]
  implicit def dynamicToccsArmatureMovementDispatcher(d: types.DynObject):ccsArmatureMovementDispatcher = d.asInstanceOf[ccsArmatureMovementDispatcher]
  implicit def dynamicToccsBaseTriggerCondition(d: types.DynObject):ccsBaseTriggerCondition = d.asInstanceOf[ccsBaseTriggerCondition]
  implicit def dynamicToccsBaseTriggerAction(d: types.DynObject):ccsBaseTriggerAction = d.asInstanceOf[ccsBaseTriggerAction]
  implicit def dynamicToccsTriggerObj(d: types.DynObject):ccsTriggerObj = d.asInstanceOf[ccsTriggerObj]
  implicit def dynamicToccEditBoxDelegate(d: types.DynObject):ccEditBoxDelegate = d.asInstanceOf[ccEditBoxDelegate]
  implicit def dynamicToccEditBox(d: types.DynObject):ccEditBox = d.asInstanceOf[ccEditBox]
  implicit def dynamicToccControl(d: types.DynObject):ccControl = d.asInstanceOf[ccControl]
  implicit def dynamicToccControlButton(d: types.DynObject):ccControlButton = d.asInstanceOf[ccControlButton]
  implicit def dynamicToccControlColourPicker(d: types.DynObject):ccControlColourPicker = d.asInstanceOf[ccControlColourPicker]
  implicit def dynamicToccControlHuePicker(d: types.DynObject):ccControlHuePicker = d.asInstanceOf[ccControlHuePicker]
  implicit def dynamicToccControlPotentiometer(d: types.DynObject):ccControlPotentiometer = d.asInstanceOf[ccControlPotentiometer]
  implicit def dynamicToccControlSaturationBrightnessPicker(d: types.DynObject):ccControlSaturationBrightnessPicker = d.asInstanceOf[ccControlSaturationBrightnessPicker]
  implicit def dynamicToccControlSlider(d: types.DynObject):ccControlSlider = d.asInstanceOf[ccControlSlider]
  implicit def dynamicToccControlStepper(d: types.DynObject):ccControlStepper = d.asInstanceOf[ccControlStepper]
  implicit def dynamicToccControlSwitch(d: types.DynObject):ccControlSwitch = d.asInstanceOf[ccControlSwitch]
  implicit def dynamicToccControlSwitchSprite(d: types.DynObject):ccControlSwitchSprite = d.asInstanceOf[ccControlSwitchSprite]
  implicit def dynamicToccRGBA(d: types.DynObject):ccRGBA = d.asInstanceOf[ccRGBA]
  implicit def dynamicToccInvocation(d: types.DynObject):ccInvocation = d.asInstanceOf[ccInvocation]
  implicit def dynamicToccSpacer(d: types.DynObject):ccSpacer = d.asInstanceOf[ccSpacer]
  implicit def dynamicToccMenuPassive(d: types.DynObject):ccMenuPassive = d.asInstanceOf[ccMenuPassive]
  implicit def dynamicToccScrollView(d: types.DynObject):ccScrollView = d.asInstanceOf[ccScrollView]
  implicit def dynamicToccSortableObject(d: types.DynObject):ccSortableObject = d.asInstanceOf[ccSortableObject]
  implicit def dynamicToccSortedObject(d: types.DynObject):ccSortedObject = d.asInstanceOf[ccSortedObject]
  implicit def dynamicToccArrayForObjectSorting(d: types.DynObject):ccArrayForObjectSorting = d.asInstanceOf[ccArrayForObjectSorting]
  implicit def dynamicToccTableViewCell(d: types.DynObject):ccTableViewCell = d.asInstanceOf[ccTableViewCell]
  implicit def dynamicToccTableViewDelegate(d: types.DynObject):ccTableViewDelegate = d.asInstanceOf[ccTableViewDelegate]
  implicit def dynamicToccTableViewDataSource(d: types.DynObject):ccTableViewDataSource = d.asInstanceOf[ccTableViewDataSource]
  implicit def dynamicToccTableView(d: types.DynObject):ccTableView = d.asInstanceOf[ccTableView]
  implicit def dynamicTospSkeleton(d: types.DynObject):spSkeleton = d.asInstanceOf[spSkeleton]
  implicit def dynamicTospSkeletonAnimation(d: types.DynObject):spSkeletonAnimation = d.asInstanceOf[spSkeletonAnimation]
}
